### ISSUE TITLE
On Mac Big Sur using an M1 mac: doesn't display anything after clicking "Load Input Display"

### ISSUE THREAD

**Issue by CarlosHartmann** [slashinfty/nincid#9]
Hey there,

As the title says, I'm on an M1 Mac. The starting menu loads for me and I can select the USB port and the console. "Load Custom Skin" doesn't work. "Load Input Display" gives me a blank window.

I would love to have this fixed as I'm not aware of any other input displayer for Mac.

**Comment by slashinfty** [comment]
I do not have a Mac to test on. If you have Node.js and yarn installed on your Mac, you can [clone the repository](https://github.com/slashinfty/nincid/blob/master/README.md#cloning) and uncomment [this line](https://github.com/slashinfty/nincid/blob/master/main/index.js#L35) to get the dev console to open. Any errors should be in the console.

**Comment by CarlosHartmann** [comment]
Thanks for your answers.

It worked better when cloning and installing the repository. It now actually loads a button display. However, it now has a problem it didn't have before. Namely, I cannot select the port because the object doesn't load. In the terminal, I get this message:

`Electron: Loading non-context-aware native module in renderer: '/Users/Carlitos/nincid/node_modules/@serialport/bindings/build/Release/bindings.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.`

The dev console gives these errors:

```
electron/js2c/renderer_init.js:115 Unable to load preload script: /Users/Carlitos/nincid/main/preload.js
(anonymous) @ electron/js2c/renderer_init.js:115
electron/js2c/renderer_init.js:115 Error: The module '/Users/Carlitos/nincid/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:815)
    at Module._load (internal/modules/cjs/loader.js:727)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:852)
    at require (internal/modules/cjs/helpers.js:74)
    at bindings (/Users/Carlitos/nincid/node_modules/bindings/bindings.js:112)
    at Object.<anonymous> (/Users/Carlitos/nincid/node_modules/@serialport/bindings/lib/darwin.js:2)
(anonymous) @ electron/js2c/renderer_init.js:115
/Users/Carlitos/nincid/node_modules/bindings/bindings.js:121 Uncaught Error: The module '/Users/Carlitos/nincid/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:815)
    at Module._load (internal/modules/cjs/loader.js:727)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:852)
    at require (internal/modules/cjs/helpers.js:74)
    at bindings (/Users/Carlitos/nincid/node_modules/bindings/bindings.js:112)
    at Object.<anonymous> (/Users/Carlitos/nincid/node_modules/@serialport/bindings/lib/darwin.js:2)
electron/js2c/renderer_init.js:15 (electron) Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.
log @ electron/js2c/renderer_init.js:15
e.startsWith.WebFrame.<computed> @ electron/js2c/renderer_init.js:87
warnAboutInsecureCSP @ electron/js2c/renderer_init.js:135
logSecurityWarnings @ electron/js2c/renderer_init.js:135
(anonymous) @ electron/js2c/renderer_init.js:135
async function (async)
(anonymous) @ electron/js2c/renderer_init.js:135

```

When trying to load, it will of course give a warning about the port not being defined.

**Comment by slashinfty** [comment]
In the cloning instructions in the readme, there are three lines on how to fix that error.

**Comment by CarlosHartmann** [comment]
My bad. Unfortunately, there is a new error message. I get it when entering `./node_modules/.bin/electron-rebuild`, the last step in the readme. When starting afterwards, the same bug persists.

```
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.15.2 | darwin | x64
gyp info find Python using Python version 3.8.5 found at "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3"
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/Carlitos/nincid/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Carlitos/nincid/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Carlitos/nincid/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Carlitos/.electron-gyp/9.4.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Carlitos/.electron-gyp/9.4.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Carlitos/nincid/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Carlitos/.electron-gyp/9.4.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Carlitos/nincid/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/Carlitos/nincid/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/Carlitos/nincid/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=9.4.4" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/Carlitos/nincid/node_modules/@serialport/bindings
gyp ERR! node -v v14.15.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.15.2 | darwin | x64
gyp info find Python using Python version 3.8.5 found at "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3"
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/Carlitos/nincid/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Carlitos/nincid/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Carlitos/nincid/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Carlitos/.electron-gyp/9.4.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Carlitos/.electron-gyp/9.4.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Carlitos/nincid/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Carlitos/.electron-gyp/9.4.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Carlitos/nincid/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/Carlitos/nincid/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/Carlitos/nincid/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=9.4.4" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/Carlitos/nincid/node_modules/@serialport/bindings
gyp ERR! node -v v14.15.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/Carlitos/nincid/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/Carlitos/nincid/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/Carlitos/nincid/node_modules/rxjs/internal/Subscriber.js:143:22)
```

**Comment by CarlosHartmann** [comment]
I made some progress.

I first installed gyp using `npm install -g node-gyp` and then re-installed Xcode with the standard `xcode-select --install`. I had some trouble with Xcode in another context, that might have interfered.

It rebuilds, executes, and loads the inputs fine now. It doesn't display the inputs though and the console error is the following:

```
Uncaught ReferenceError: skinJson is not defined
    at display_interface.js:217
    at Array.forEach (<anonymous>)
    at readPort (display_interface.js:213)
    at loadDisplay (display_interface.js:137)
    at HTMLButtonElement.onclick (index.html:54)
```

Let me know if I should open a new issue for this. And of course, let me know if the fault is again mine and what I can do to fix it.

**Comment by slashinfty** [comment]
Looks like that was a legit problem. I have fixed it. You can either pull the latest code, or just make [these changes](https://github.com/slashinfty/nincid/commit/0967d913d9d2f5ad1606f0445f6e367d05a9add5).

**Comment by CarlosHartmann** [comment]
It works now! It loads without any problems and the inputs are displayed.

Only the joystick isn't displayed but this seems to be outside of the software as another solution I tried also struggled with the joystick. This issue is resolved then.
